### ISSUE TITLE
Nice work! How to solve this error in unity? Thank you!

### ISSUE THREAD

**Issue by gascendcn** [chrislarkee/ParaView_CFD_To_VR#1]
error: Assets\Scripts\GlobalControl.cs(25,22): error CS0103: The name 'OVRInput' does not exist in the current context

**Comment by chrislarkee** [comment]
You'll need to add the [Oculus Integration package](https://assetstore.unity.com/packages/tools/integration/oculus-integration-82022) from the Unity Asset Store to the project. I don't redistribute that package due to its license.
